  6-311++G*  EMSL  Basis Set Exchange Library  11/30/16 1:19 PM
 Elements                             References
 --------                             ----------
 H Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca:  .
 H, Li - Ne: R. Krishnan, J.S. Binkley, R. Seeger and J.A. Pople,
 J. Chem. Phys. 72, 650 (1980)
 Na - Ar:    A.D. McLean and G.S. Chandler J. Chem. Phys. 72, 5639, (1980).
 K  - Ca:    J-P. Blaudeau, M. P. McGrath, L.A. Curtiss and L. Radom,
 J. Chem. Phys. 107, 5016 (1997).
 6-311G* Polarization Functions
 -------------------------------
 Elements                            Reference
 H - He: (1p) R. Krishnan, J.S. Binkley, R. Seeger and J.A. Pople, J. Chem.
 Li - Ne: (1d) Phys. 72, 650 (1980).
 Note: This basis uses 5-component d functions.
 This collection of polarization functions was chosen to give the lowest
 possible energy for the atomic ground states in frozen core UMP2
 calculations. For Be all exponents were optimized for the 1s2 2s1 2p1
 excited 2-P state.
 Diffuse functions:
 H, Li-Cl: T. Clark, J. Chandrasekhar,  G.W. Spitznagel, P.V.R. Schleyer,
 J. Comp. Chem. 4, 294 (1983).

O-HYDROGEN H (6-311++G.D) BASIS TYPE: 1 
#
4
1    0    3
 33.8650000              0.0254938        
  5.0947900              0.1903730        
  1.1587900              0.8521610        
2    0    1
  0.3258400              1.0000000        
3    0    1
  0.1027410              1.0000000        
4    0    1
  0.0360000              1.0000000        

O-OXYGEN O (6-311++G.D) BASIS TYPE: 1
#
10
1    0    6
8588.5000000              0.00189515       
1297.2300000              0.0143859        
 299.2960000              0.0707320        
  87.3771000              0.2400010        
  25.6789000              0.5947970        
   3.7400400              0.2808020        
 2    0    3
  42.1175000              0.1138890        
   9.6283700              0.9208110        
   2.8533200             -0.00327447       
 3    0    1
   0.9056610              1.0000000        
 4    0    1
   0.2556110              1.0000000        
 5    0    1
   0.0845000              1.0000000        
 2    1    3
  42.1175000              0.0365114        
   9.6283700              0.2371530        
   2.8533200              0.8197020        
 3    1    1
   0.9056610              1.0000000        
 4    1    1
   0.2556110              1.0000000        
 5    1    1
   0.0845000              1.0000000        
 3    2    1
   1.2920000              1.0000000

