      subroutine fourIndexTransformation(numberOfContractions,
     *     otherNumberOfContractions
     *     ,nameFile,nproc,integralStackSize)
!----------------------------------------------------------------------
!  DESCRIPTION : This routine 
!                is main program of symmetry adapted four-index 
!                integral transformation.
!  AUTHORS :     Shigeyoshi YAMAMOTO and Umpei NAGASHIMA (2003)
!  RELEASE :     v.01  gen = S.Yamamoto (sya) 2003-03-29 at chukyo-u
!----------------------------------------------------------------------
!  Files
!     FT71 : inf.dat / old / sequential / unformatted 
!     FT72 : mocoef.dat / old / sequential / unformatted / 
!     FT73 : soint.dat / old / sequential / unformatted /
!     FT74 : moint.dat / new / sequential / unformatted /
!
!     FT91 : work / direct / unformatted / ordering bin-1
!     FT92 : work / direct / unformatted / ordering bin-2
!     FT93 : work / sequential / unformatted / ordering control data
!     FT94 : work / sequential / unformatted / da2s
!     FT95 : work / direct / unformatted / half-transformed integrals
!----------------------------------------------------------------------
!  Data flow
!     ordering step (WTO*)
!       FT73: SO integrals generated by prepar.exe
!         -> 1st stage of ordering
!       FT91: work direct file (bin-1)
!         -> 2nd stage of ordering
!       FT92: work direct file (bin-2)
!
!     merge step  (WTS*)
!       FT94: work sequential file 
!
!     transformation step (WTH*)
!       FT95: half-transformed integrals, direct-access file
!       FT74: final transformed integrals, sequential file 
!
!----------------------------------------------------------------------
      IMPLICIT NONE
      INCLUDE 'declar.h'
      INCLUDE 'sym4tr.h'
!
!     ...memory size
!
      integer :: numberOfContractions
      integer :: otherNumberOfContractions
      character(*) :: nameFile
      INTEGER,PARAMETER :: LDMB = 256 !800 ! MB
      INTEGER,PARAMETER :: LDBYTE = LDMB * 10**6 ! Byte
      INTEGER,PARAMETER :: LD8BYT = LDBYTE/LDREAL ! 8-Byte
      integer :: nproc
      integer :: integralStackSize
      CHARACTER(LEN=60) :: FN61 
      CHARACTER(LEN=60) :: FN62 
      CHARACTER(LEN=60) :: FN63 
      CHARACTER(LEN=60) :: FN71 
      CHARACTER(LEN=60) :: FN72 
      CHARACTER(LEN=60) :: FN73 
      CHARACTER(LEN=60) :: FN74

!
!     ...allocate big array by COMMON
!
      REAL(KIND=LDREAL),DIMENSION(LD8BYT) :: BIGARY
      COMMON/BIGARY/BIGARY
      COMMON/FILES/FN61,FN62,FN63,FN71,FN72,FN73,FN74
!
!----------------------------------------------------------------------

     
      FN61 = trim(nameFile)//'inf'	    
      FN62 = trim(nameFile)//'mo.values'    
      FN63 = trim(nameFile)//'.ints' 
      FN71 = trim(nameFile)//'inf.dat'	    
      FN72 = trim(nameFile)//'mocoef.dat'   
      FN73 = trim(nameFile)//'aoints.dat'    
      FN74 = trim(nameFile)//'moint.dat'

      CALL WMINIT

!
!
      CALL WMINPT(numberOfContractions, 1D-10, 1D-10, 1D-10)
!
!     ...check consistency of input data and save them
!
      CALL WMINFO

!     ...set integral file and mo coefficient file
!
      CALL WMFILE(LD8BYT,BIGARY,nproc,integralStackSize, 
     * otherNumberOfContractions)
!
!     ...check block-diagonality of MO matrix
!
      CALL WMCHKD(LD8BYT,BIGARY)

!     ...set control data
!
      CALL WTINIT
!
!     ...ordering SO integrals
!
      CALL WTODRV(LD8BYT,BIGARY)
!
!     ...copy ordered SO integrals from direct access file into 
!        sequential file
!
      CALL WTSDRV(LD8BYT,BIGARY)
!
!     ...integral transformation
!
      CALL WTHDRV(LD8BYT,BIGARY)
!
!      CALL PRCPUT('SYM4TR ended',0)
!
      end subroutine fourIndexTransformation
